### ISSUE TITLE
Exception flow

### ISSUE THREAD

**Issue by songofthewings** [VitaI55/phplab-tasks#1]
Please make changes for all 3 functions:
If condition with throw exception inside is met, nothing in this function will execute after throw. So please make your code simpler by removing 'else'  after that.

https://github.com/VitaI55/phplab-tasks/blob/72a7bd2bf017f3cbcb4bbe064dced32d47f7b396/src/01-basics.php#L17

**Comment by VitaI55** [comment]
fixed
