### ISSUE TITLE
Else if statement

### ISSUE THREAD

**Issue by songofthewings** [VitaI55/phplab-tasks#3]
Please make all 'else if' conditions in your code according to PSR-12:
`The keyword elseif SHOULD be used instead of else if so that all control keywords look like single words.`

https://github.com/VitaI55/phplab-tasks/blob/72a7bd2bf017f3cbcb4bbe064dced32d47f7b396/src/01-basics.php#L21

**Comment by VitaI55** [comment]
Fixed
