### ISSUE TITLE
 Control Structures according with PSR-12

### ISSUE THREAD

**Issue by songofthewings** [VitaI55/phplab-tasks#4]
Please make all if condition structures in according with PSR-12 - remove a blank line after opening brace:
`The body MUST be on the next line after the opening brace`

https://github.com/VitaI55/phplab-tasks/blob/72a7bd2bf017f3cbcb4bbe064dced32d47f7b396/src/01-basics.php#L15

**Comment by VitaI55** [comment]
Fixed

**Comment by songofthewings** [comment]
not fixed
