### ISSUE TITLE
isLeapYear

### ISSUE THREAD

**Issue by songofthewings** [VitaI55/phplab-tasks#5]
It wouldn't work if you didn't change function signature from task. This will not work also with strict_types=1 mode.
Please change this to return boolean, not string.
https://github.com/VitaI55/phplab-tasks/blob/9507251307e11aec235a95aa7edad05ef5acb310/src/01-basics.php#L49

**Comment by VitaI55** [comment]
This time I used simpler solve with logical operands instead o date()

**Comment by apopova-cartera** [comment]
You could leave date, just cast return value to bool. Because function signature should be unchanged.
