### ISSUE TITLE
Control Structures according with PSR-12

### ISSUE THREAD

**Issue by songofthewings** [VitaI55/phplab-tasks#6]
Not all cases fixed:
Please make all if condition structures in according with PSR-12 - remove a blank line after opening brace:
`The body MUST be on the next line after the opening brace`

https://github.com/VitaI55/phplab-tasks/blob/9507251307e11aec235a95aa7edad05ef5acb310/src/01-basics.php#L18

**Comment by VitaI55** [comment]
Fixed with return keyword
