### ISSUE TITLE
This logic does not work when a noun begins with a capital letter

### ISSUE THREAD

**Issue by mlyahovi** [VitaI55/phplab-tasks#8]
This logic does not work when a noun begins with a capital letter
https://github.com/VitaI55/phplab-tasks/blob/1cdbd181b52c82ab66e35f960235b2f5bb489e86/src/02-strings.php#L60

**Comment by songofthewings** [comment]
done

**Comment by mlyahovi** [comment]
> done

Still not working

**Comment by songofthewings** [comment]
Implemented functionality doesn't work as required if $noun consists uppercase letters inside (not only first).

**Comment by VitaI55** [comment]
Fixed
